---
dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/requirements.yml

driver:
  name: default
  options:
    managed: false

platforms:
  - name: bridge-1
    groups:
      - proxmox
      - wifi_nodes
  - name: bridge-2
    groups:
      - proxmox
      - wifi_nodes

provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
      collections_paths: ${MOLECULE_PROJECT_DIRECTORY}/collections
      host_key_checking: false
      retry_files_enabled: false
    ssh_connection:
      pipelining: true
  env:
    BRIDGE_1_API_TOKEN: ${BRIDGE_1_API_TOKEN}
    BRIDGE_2_API_TOKEN: ${BRIDGE_2_API_TOKEN}
    BRIDGE_1_HOST: ${BRIDGE_1_HOST}
    BRIDGE_2_HOST: ${BRIDGE_2_HOST}
    MESH_KEY: ${MESH_KEY}
  inventory:
    links:
      host_vars: ../../inventory/host_vars/
      group_vars: ../../inventory/group_vars/

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - syntax
    - cleanup
    - converge
    - verify
    - cleanup
