#!/bin/sh /etc/rc.common
# procd init script for the callhome command HTTP endpoint.
# uhttpd serves CGI on port 9002.
START=99
USE_PROCD=1

start_service() {
    procd_open_instance callhome_cmd
    procd_set_param command /usr/sbin/uhttpd \
        -p 0.0.0.0:9002 \
        -h /www \
        -x /cgi-bin \
        -n 2 \
        -T 30
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
