---
dependencies: []

galaxy_info:
  author: kyle
  license: proprietary
  role_name: wireguard_lxc
  description: Provision a WireGuard VPN LXC container on Proxmox VE
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
