---
wireguard_ct_hostname: wireguard
wireguard_ct_memory: 128
wireguard_ct_cores: 1
wireguard_ct_disk: "1"
wireguard_ct_template_path: "{{ wireguard_lxc_template_path }}"
wireguard_ct_onboot: true
wireguard_ct_startup_order: 2
wireguard_ct_features:
  - "nesting=1"
