---
dependencies: []

galaxy_info:
  author: kyle
  license: proprietary
  role_name: rsyslog_lxc
  description: Provision an rsyslog centralized log collector LXC container on Proxmox VE
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
