---
dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/requirements.yml

driver:
  name: default
  options:
    managed: false

platforms:
  - name: home
    groups:
      - proxmox
      - router_nodes
      - vpn_nodes
      - dns_nodes
      - wifi_nodes
      - monitoring_nodes
      - service_nodes
      - media_nodes
      - desktop_nodes
  - name: mesh1
    groups:
      - proxmox
      - lan_hosts
      - vpn_nodes
      - wifi_nodes
  - name: ai
    groups:
      - proxmox
      - vpn_nodes
  - name: mesh2
    groups:
      - proxmox
      - vpn_nodes
      - wifi_nodes

provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
      collections_paths: ${MOLECULE_PROJECT_DIRECTORY}/collections
      host_key_checking: false
      retry_files_enabled: false
    ssh_connection:
      pipelining: true
  env:
    HOME_API_TOKEN: ${HOME_API_TOKEN}
    MESH1_API_TOKEN: ${MESH1_API_TOKEN}
    MESH2_API_TOKEN: ${MESH2_API_TOKEN}
    AI_API_TOKEN: ${AI_API_TOKEN}
    PRIMARY_HOST: ${PRIMARY_HOST}
    AI_HOST: ${AI_HOST}
    MESH_2_HOST: ${MESH_2_HOST}
    MESH_KEY: ${MESH_KEY}
  inventory:
    links:
      host_vars: ../../inventory/host_vars/
      group_vars: ../../inventory/group_vars/

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - cleanup
    - syntax
    - converge
    - verify
    - cleanup
