---
- name: Provision Kiosk LXC container
  hosts: kiosk_nodes
  gather_facts: false
  roles:
    - kiosk_lxc

- name: Configure Kiosk
  hosts: kiosk_nodes
  gather_facts: false
  roles:
    - kiosk_configure
