---
kodi_ct_hostname: kodi
kodi_ct_memory: 1024
kodi_ct_cores: 2
kodi_ct_disk: "4"
kodi_ct_template_path: "{{ kodi_lxc_template_path }}"
kodi_ct_onboot: false
kodi_ct_unprivileged: false
kodi_ct_features:
  - "nesting=1"
kodi_ct_ip_offset: "{{ kodi_ct_ip_offset | default(16) }}"
