---
kiosk_ct_hostname: kiosk
kiosk_ct_memory: 1024
kiosk_ct_cores: 2
kiosk_ct_disk: "4"
kiosk_ct_template_path: "{{ kiosk_lxc_template_path }}"
kiosk_ct_onboot: true
kiosk_ct_unprivileged: false
kiosk_ct_features:
  - "nesting=1"
kiosk_ct_startup_order: 6
