---
kiosk_ct_hostname: kiosk
kiosk_ct_memory: 512
kiosk_ct_cores: 1
kiosk_ct_disk: "2"
kiosk_ct_template: "{{ kiosk_lxc_template }}"
kiosk_ct_template_path: "{{ kiosk_lxc_template_path }}"
kiosk_ct_onboot: true
kiosk_ct_unprivileged: false
kiosk_ct_features:
  - "nesting=1"
kiosk_ct_ip_offset: "{{ kiosk_ct_ip_offset | default(19) }}"
