---
- name: Validate rsyslog config
  ansible.builtin.command:
    cmd: /usr/sbin/rsyslogd -N1
  listen: _restart_rsyslog
  changed_when: false

- name: Restart rsyslog service
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
  listen: _restart_rsyslog
