---
- name: Detect infrastructure on desktop nodes
  hosts: desktop_nodes
  gather_facts: true
  roles:
    - proxmox_bridges
    - proxmox_igpu

- name: Provision Desktop LXC
  hosts: desktop_nodes
  gather_facts: false
  roles:
    - desktop_lxc
    - role: deploy_stamp
      vars:
        deploy_stamp_play: desktop_lxc

- name: Configure Desktop LXC
  hosts: desktop_nodes
  gather_facts: false
  roles:
    - desktop_configure
